# Generated by Django 2.2.4 on 2019-10-04 06:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='blood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bgroup', models.CharField(max_length=2)),
                ('hname', models.CharField(default='', max_length=50)),
                ('stock', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='medicine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('med_name', models.CharField(max_length=20)),
                ('hname', models.CharField(default='', max_length=50)),
                ('stock', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='req_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hname', models.CharField(max_length=50)),
                ('d_hname', models.CharField(default='', max_length=50)),
                ('timestamp', models.DateTimeField(default=datetime.datetime(2019, 10, 4, 6, 8, 58, 670845, tzinfo=utc))),
                ('entity', models.CharField(max_length=20)),
                ('product', models.CharField(default='', max_length=50)),
                ('no_stock', models.IntegerField(default=0)),
                ('delivered_status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('username', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('password', models.TextField()),
                ('hname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField(default='')),
                ('timestamp', models.DateTimeField(default=datetime.datetime(2019, 10, 4, 6, 8, 58, 669845, tzinfo=utc))),
            ],
        ),
    ]
